[build]
  # Usa pnpm para construir
  command = "pnpm build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/OneSignalSDKWorker.js"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/OneSignalSDKUpdaterWorker.js"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache"
